import uuid
from flask import Flask, request, jsonify
import os, json
from groq import Groq
from dotenv import load_dotenv
app = Flask(__name__)

load_dotenv()
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

def llm_signal(text):
    prompt = (
        "You are an AI-text detector. Assess whether the following text was "
        "written by a human or generated by AI. Respond with ONLY a JSON object "
        'of the form {"ai_likelihood": <number between 0 and 1>}, where 1 means '
        "definitely AI-generated and 0 means definitely human-written.\n\n"
        f"TEXT:\n{text}"
    )
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
    )
    raw = response.choices[0].message.content
    result = json.loads(raw)
    return float(result["ai_likelihood"])

@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json()
    text = data.get("text")
    creator_id = data.get("creator_id")

    content_id = str(uuid.uuid4())
    llm_score = llm_signal(text)
    if llm_score > 0.75:
        attribution = "likely_ai"
    elif llm_score < 0.4:
        attribution = "likely_human"
    else:
        attribution = "uncertain"

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": llm_score,
        "label": "placeholder label",
    })

if __name__ == "__main__":
    app.run(port=5001, debug=True)