import uuid
from flask import Flask, request, jsonify
import os, json
from groq import Groq
from dotenv import load_dotenv
import sqlite3
from datetime import datetime, timezone
import re
import statistics

DB_PATH = "audit_log.db"

def make_label(attribution):
    labels = {
        "likely_ai": "This content shows strong signs of being AI-generated. Our system is fairly confident, but automated detection isn't perfect — the creator can appeal this assessment.",
        "likely_human": "This content appears to be human-written. No strong signs of AI generation were detected.",
        "uncertain": "We can't confidently determine whether this was written by a human or AI. Treat this result with caution.",
    }
    return labels[attribution]

def stylometry_signal(text):
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    words = re.findall(r"\b\w+\b", text.lower())

    # Guard: too short for meaningful stats -> neutral 
    if len(sentences) < 2 or len(words) < 10:
        return 0.5

    # Metric 1: sentence-length variance. Low variance = uniform = AI-like.
    lengths = [len(re.findall(r"\b\w+\b", s)) for s in sentences]
    stdev = statistics.pstdev(lengths)
    variance_ai = 1 - min(max((stdev - 4) / (8 - 4), 0), 1)  # stdev 2->1.0(AI), 10->0.0(human)

    # Metric 2: type-token ratio (vocab diversity). Lower diversity = more AI-like.
    ttr = len(set(words)) / len(words)
    ttr_ai = 1 - min(max((ttr - 0.80) / (0.95 - 0.80), 0), 1)    # ttr 0.4->1.0(AI), 0.7->0.0(human)

    return round(0.7 * variance_ai + 0.3 * ttr_ai, 3)

def init_db():
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS audit_log (
                content_id      TEXT,
                creator_id      TEXT,
                timestamp       TEXT,
                attribution     TEXT,
                confidence      REAL,
                llm_score       REAL,
                stylo_score     REAL,
                status          TEXT,
                appeal_reasoning TEXT
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS submissions (
                content_id  TEXT PRIMARY KEY,
                creator_id  TEXT,
                text        TEXT,
                attribution TEXT,
                confidence  REAL,
                status      TEXT
            )
        """)

def log_event(entry):
    entry = {
        "appeal_reasoning": None,   # default; appeals override this
        **entry,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "INSERT INTO audit_log "
            "(content_id, creator_id, timestamp, attribution, confidence, llm_score, stylo_score, status, appeal_reasoning) "
            "VALUES (:content_id, :creator_id, :timestamp, :attribution, :confidence, :llm_score, :stylo_score, :status, :appeal_reasoning)",
            entry,
        )

def read_log(limit=20):
    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM audit_log ORDER BY timestamp DESC LIMIT ?", (limit,)
        ).fetchall()
    return [dict(r) for r in rows]

app = Flask(__name__)
init_db()

load_dotenv()
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

def llm_signal(text):
    prompt = (
        "You are an AI-text detector. Assess whether the following text was "
        "written by a human or generated by AI. Respond with ONLY a JSON object "
        'of the form {"ai_likelihood": <number between 0 and 1>}, where 1 means '
        "definitely AI-generated and 0 means definitely human-written.\n\n"
        f"TEXT:\n{text}"
    )
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
    )
    raw = response.choices[0].message.content
    result = json.loads(raw)
    return float(result["ai_likelihood"])

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    content_id = data.get("content_id")
    reasoning = data.get("creator_reasoning")

    # Look up the original submission
    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        row = conn.execute(
            "SELECT * FROM submissions WHERE content_id = ?", (content_id,)
        ).fetchone()

    if row is None:
        return jsonify({"error": "content_id not found"}), 404

    # Update the submission's status
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "UPDATE submissions SET status = ? WHERE content_id = ?",
            ("under_review", content_id),
        )

    # Log the appeal alongside the original decision
    log_event({
        "content_id": content_id,
        "creator_id": row["creator_id"],
        "attribution": row["attribution"],
        "confidence": row["confidence"],
        "llm_score": None,
        "stylo_score": None,
        "status": "under_review",
        "appeal_reasoning": reasoning,
    })

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal was received and is under review.",
    })

@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json()
    text = data.get("text")
    creator_id = data.get("creator_id")

    content_id = str(uuid.uuid4())
    llm_score = llm_signal(text)
    stylo_score = stylometry_signal(text)
    ai_likelihood = round(0.7 * llm_score + 0.3 * stylo_score, 3)

    if ai_likelihood > 0.75:
        attribution = "likely_ai"
    elif ai_likelihood < 0.4:
        attribution = "likely_human"
    else:
        attribution = "uncertain"

    label = make_label(attribution)

    # Save to mutable submissions table (so appeals can look it up + update status)
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            "INSERT INTO submissions (content_id, creator_id, text, attribution, confidence, status) "
            "VALUES (?, ?, ?, ?, ?, ?)",
            (content_id, creator_id, text, attribution, ai_likelihood, "classified"),
        )

    log_event({
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": ai_likelihood,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "status": "classified",
    })

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": ai_likelihood,
        "label": label,
    })
@app.route("/log", methods=["GET"])
def view_log():
    return jsonify({"entries": read_log()})

if __name__ == "__main__":
    app.run(port=5001, debug=True)